- hosts: all
  tasks:
    - name: uninstaller dosyası indiriliyor
      become: true
      get_url:
        url: https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh        
        dest: /tmp
        mode: '0777'

    - name: kaldırma sağlanıyor
      become: true
      shell: /tmp/netdata-uninstaller.sh --yes --force --env /opt/netdata/etc/netdata/.environment

    - name: indirilen dosya siliniyor
      file:
        path: /tmp/netdata-uninstaller.sh
        state: absent
