- hosts: all
  tasks:
    - name: uninstaller dosyası indiriliyor 
      become: true
      shell: wget -P /tmp/ https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
      
    - name: yetki veriliyor
      become: true
      shell: chmod +x /tmp/./netdata-uninstaller.sh
      
      
